### ISSUE TITLE
ns conflicts 

### ISSUE THREAD

**Issue by tongqqiu** [edlich/clarango#10]
I got the following error when including both core ad document ns
CompilerException java.lang.IllegalStateException: write already refers to: #'cheshire.core/write in namespace: clarango.utilities.http-utility, compiling:(clarango/utilities/http_utility.clj:1:1) 

Here is the code
```
(ns myapp.test-arango
  (:require [clarango.core :refer [set-connection! set-default-db!]]
            [clarango.document :refer [create]]))
```

**Comment by Lepetere** [comment]
I've never encountered that one. Well there is no `write` method in the `document` or the `core` namespace, it seems like there is a name conflict between the libraries we are using..? But it's really strange that this only seems to happen for you.

**Comment by tongqqiu** [comment]
It is due to that I use some newer version of libraries in my project. I create a pull request for that, to upgrade the libraries.  
https://github.com/edlich/clarango/pull/11

**Comment by Lepetere** [comment]
Cool, thanks for contributing!
