### ISSUE TITLE
collection/get-delayed-collection is broken

### ISSUE THREAD

**Issue by Lepetere** [edlich/clarango#12]
It broke with merge request #9. The call of `collection/get-all-documents` inside the method needs to be fixed.

**Comment by mikeholmesuk** [comment]
@Lepetere - do you have a test that can be used around this? Or an indication of how I can recreate the problem please? I'm using ArangoDB 2.6.2 and running the existing tests doesn't catch any problems around `get-delayed-collection`.

**Comment by Lepetere** [comment]
There is a delayed collection test, I think in the document test namespace, sorry I can't check now. When you run the tests you will notice that the output of that test is empty. The fact that the test is not failing because of this is less than optimal and I'm sorry for the poor quality of the tests.

**Comment by Lepetere** [comment]
Fixed with https://github.com/edlich/clarango/commit/148b8dde88b75fbcdd4a3e7d1d4d25196b562605.
