### ISSUE TITLE
clarango.graph does not support multi collection graphs

### ISSUE THREAD

**Issue by mikeholmesuk** [edlich/clarango#15]
ArangoDB has supported multi-collection graphs since version 2.2 (see [here](https://www.arangodb.com/2014/07/multi-collection-graphs/) ) but the current version of clarango does not appear to. Creating a multi-collection graph through the web-console will generate the following error if trying to `get-info` from clarango:

```java.lang.Exception: Clarango: There was an error trying to access a resource: clj-http: status 404; body: {"error" true, "code" 404, "errorNum" 1901, "errorMessage" "Graph can not be loaded, because more than 1 vertex collection is defined. Please use the new graph module"```

Mostly this appears to be because functions in the current `clarango.graph`(except for, rather oddly, the `create-vertex` function) use `_api/graph` instead of the updated `_api/gharial` end-points. This same problem exists when creating new graph databases as they use the deprecated `graph` end-points and as such can only be used to create single collection graphs.

All graph operations should be updated to support multi-collection graphs. If this is not backwards compatible then the fact that this is a breaking change should be highlighted.

* I'm using ArangoDB 2.6.2 via the [ArangoDB docker](https://github.com/arangodb/arangodb-docker) image

**Comment by mikeholmesuk** [comment]
I know I raised this but I'm happy enough to pick this up as I really need the functionality. Looking at it, the main problem is with the create graph function and including a mechanism to amend them once they are created. 

The current API allows for creating multiple collections at either the 'from' or the 'to' end of the relationship. An example body for creating a multi-model graph is as follows:

`{"name":"<my_graph_name>","edgeDefinitions":[{"collection":"<my_edge_collection_name>","from":["<coll_1>", "<coll_2>"],"to":["<coll_3>", "<coll_4>", "<coll_5>"]}]`

I would suggest that an appropriate signature for the create function should take the `graph-name`, the `edge-collection` (so changing the order here) and a `from-collection` and `to-collection` (both of which could be either single entries or vectors of entries which will ultimately be entered as vectors of one if the latter) OR the `graph-name`, the `vertices-collection` and the `edges-collection` (as it is at the moment but define the function to map the vertices collection to itself under the covers) AND have a multi-collection `create` function (named `create-multi` perhaps) which takes a graph name and a vector of maps in the format `[{:edge_name <edge-name> :from [<from_collection (keyword/string)>] :to [<to_collection (keyword/string)>]}]`

What do people think?

**Comment by edlich** [comment]
Dear Mike,
(sorry for being quite for so long (extreme busy)).

I totally missed this update on multi collection graphs.
Your suggestion sounds good. 
If so it would be great if you could provide the changed and the new create function and a test for this as a pull request?
I will be happy to generate a new version and the new API doc.
Best Regards
Stefan E.

**Comment by Lepetere** [comment]
@mikeholmesuk it would be great if you had the time to update the `graph` interface to fully use the new `_api/gharial` endpoint and make it possible to create multi-collection graphs. The reason why the `gharial` endpoint is only used in one method so far is, that I started implementing it, but didn't have time to finish it...

About the implementation I personally would prefer it, if the `graph/create` function itself couldn't create any graphs by itself to stay consistent with how it works currently. Instead I would prefer the creation with nesting e.g. like `(graph/create (collection\create "name1" {:type 2}) (collection\create "name2" {:type 3}))` or then for multi-collection graphs `(graph/create (collection\create-multi "name1" "name2" {:type 2}) (collection\create-multi "name3" "name4" {:type 3}))`. You know what I mean? But in the end if that's too complicated also the direct creation of the collections in the `graph/create` function is okay for me, the important thing is that it works! :)

@edlich please don't generate a new version until we fix issues #12 and #14!

**Comment by mikeholmesuk** [comment]
@Lepetere no worries. I've done most of this already and it should be do-able enough the way you propose. I'll have a go at this over the next couple of days and send out another pull-request. Should hopefully be by the end of the weekend.

**Comment by mikeholmesuk** [comment]
Hi Guys. apologies for the delay in getting a fix together for this. It turns out that the changes were not as simple as I would have hoped. It looks like the end-point structures have changed with the new graph styles and I didn't want to complicate everything (as well as risk not being backwards compatible) by doing everything within the same namespace. As such I've created a new namespace to handle the graph features available under ../gharial/... . I've added quite extensive tests around the vertices, edges and creating new graphs.

Multi-collection graphs can now be created using the following command:

`(gharial/create :test-graph [{:edge-collection "my-test-edges" :from [:people] :to [:content]}])`

I've raised a pull request https://github.com/edlich/clarango/pull/16 .

**Comment by edlich** [comment]
Dear Mike,

thanks a lot for your work.
I am travelling and only be back next week for a pull. Perhaps Peter can
help earlier.

Thanks and best
Stefan Edlich
Am 17.08.2015 19:07 schrieb "Mike Holmes" <notifications@github.com>:

**Comment by Lepetere** [comment]
Hi Stefan and Mike,
I am also travelling at the moment and will only have time to review this in 2 or 3 weeks, sorry. Thanks for the pull request anyway!

**Comment by Lepetere** [comment]
Resolved with https://github.com/edlich/clarango/pull/16.

**Comment by Lepetere** [comment]
Amendment: I'm replacing the `graph` namespace with `gharial` in the next version of Clarango `v0.7.0` and renaming it to `graph`. I think having two namespaces that deal with graphs is too confusing for new users and I don't want the driver be too cluttered with namespaces. I know that I'm sacrificing downwards compatibility with this, but we are not fully downward compatible anyway and in this case I favor a less complicated driver and namespace layout in the future over being downward compatible.
