### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by mikeholmesuk** [edlich/clarango#17]
ArangoDB supports transactions (beyond the waitForSync signal) but currently these are not part of what is available in Clarango. Personally i think the mechanism that ArangoDB offers to handle transactions (as can be seen [here](https://docs.arangodb.com/HttpTransaction/index.html)) is a phenomenally shit and half-baked solution. That said however, it's a feature that probably should be included for completeness and/or for anyone like me who really needs it.

Adding functions which can run things against `_api/transaction` will be fairly trivial. Offering the end-points and then just accepting a body which has the stringified functions is a fairly easy. What might require a little more thinking is if Clarango wants to offer some way of building what eventually becomes a javascript function (every time I say it I hate the idea of it less and less) that becomes the body of the function that is sent across. Maybe this is out of scope of the aims of the library, and I certainly wouldn't blame anybody for not wanting to touch that with a barge-pole, but I thought I'd raise it as an open issue to see if anyone had any thoughts about it.

**Comment by mikeholmesuk** [comment]
Thinking about this, there may be a nice way of generating a relevant javascript function, in an idiomatic manner, using the Clojurescript compiler. I'll admit that I haven't looked at it enough to be dangerous with regards to ClojureScript, but it may offer a useful get out from actually having to write javascript and then stringify it.

**Comment by edlich** [comment]
Dear Mike,
I have not yet digged deep into their transactions, but if you think ArangoDB could improve the concept, they are surely thankful and keen to hear about in the google groups forum! 
Anyway: To my understanding a transaction must always have a javascript part. To my understanding I would do two steps:
1) build a clojure transaction function which just receives the JavaScript as a string and pass it on!
2) If there is more time or need we might think of other JS generating functionality (as ClojureScript) but I think this requires long tough thinking to be really smart.
Can you write #1?
Best Regards
Stefan Edlich

**Comment by mikeholmesuk** [comment]
Hi Stefan,
No problem in doing #1. I'm doing a project using this library at the moment so it may take me a few days as I'm building the features as I need them and road-testing them at the same time. Given the end-point on ArangoDB would you agree that it is worth putting this into a separate namespace (`clarango.transaction`) even though it will likely be a fairly minimalist namespace? 

Agree on point #2 - it would need quite a lot of thought so am happy to leave that for now.

Regards

Mike

**Comment by edlich** [comment]
Dear Mike,

thanks for #1. As long as we do not have 100 namespaces I think its ok!

#2 then you will build it when you have time?

I will have a look at the pull request soon (internet is dead on the landline :-(
Thanks and best regards
Stefan E.

**Comment by Lepetere** [comment]
Any updates on this @mikeholmesuk ?

**Comment by mikeholmesuk** [comment]
Hiya. Apologies, I got a little waylaid on the project I was working on and haven't had much time to finish. I've been running some tests locally for this - I'm hoping to raise a pull request over the next couple of days.

**Comment by Lepetere** [comment]
Great! Keep it coming :)

**Comment by mikeholmesuk** [comment]
Pull request #19 has been raised for this. Please let me know if you would like me to clarify/ validate anything.
