### ISSUE TITLE
parameter and args wrong in get-info-user and get-collection-info-list

### ISSUE THREAD

**Issue by edlich** [edlich/clarango#2]
The errors are documented in the testfile: [database.clj](https://github.com/edlich/clarango/blob/master/src/clarango/database.clj#L22) testfile.

```clojure
  ;; error 400 "bad parameter!"
(println "*** User Access DBs: <" (db/get-info-user) ">") 

  ;; Both methods get:
  ;; Wrong number of args (4) passed to: http-utility$get-uri
(println "Collections in the default DB: <" (db/get-collection-info-list) ">")
(println "Collections in the testDB: <" (db/get-collection-info-list testdb) ">")
```

I can't explain the exceptions even as the functions take no parameter (except the last with the testdb parameter).

Furthermore I do not understand the behaviour of the `get-info-current` function as I always get back information about the system db (even if I created and changed the db before).

What's wrong here? :confused:  
Greetings Stefan

Warning: If the crash is reproduced, the testdb will be in the system and can not be created in the next test run! Hence you receive a second error first. You have you comment the error functions and the create out to get a fresh arangoDB system or delete the db in the arangosh.

**Comment by Lepetere** [comment]
I'm closing this for now since there was no new input in over a new. Should the problem still occur please reopen.
