### ISSUE TITLE
Better Testing

### ISSUE THREAD

**Issue by edlich** [edlich/clarango#5]
Currently there are only four (possible incomplete) tests for the core, database, document and index files. 
A more global test is hidden in the main.clj of the developer branch!
However the test/clarango/test in the master branch needs the following:
1. Check if the tests the four existing documents are sufficient
2. Implement tests for admin, collection, graph and query
3. Check if the tests run on Travis-CI (ArangoDB supports Travis-CI)

(if this is done step by step and file by file each step is a low hanging fruit ;-)

**Comment by Lepetere** [comment]
This issue is outdated. There have been a lot of improvements to the tests with the last pull requests. They are still far from perfect, but I think we will improve them along the way when implementing/updating features.
