### ISSUE TITLE
Implement Misc Functions :+1:

### ISSUE THREAD

**Issue by edlich** [edlich/clarango#6]
The http interface description has some miscellaneous functions.
Hence Clarango needs a misc.clj file to support them (or add them to admin.clj).
There are just six features described here:
http://docs.arangodb.org/HttpMiscellaneousFunctions/README.html
1. Get API Version: GET /_api/version
2. Flush Write Ahead Log: PUT /_admin/wal/flush 
3. Retrieve WAL conf: PUT /_admin/wal/flush
4. Configure WAL: PUT /_admin/wal/properties
5. Guess what: GET /_admin/time
6. Return current request: GET /_admin/echo
They should be easy to implement with the http-, core- and uri-utility tools.

**Comment by Lepetere** [comment]
This issue is out of date (ArangoDB's interface changed plus some misc funtions were already implemented).
