### ISSUE TITLE
Implement User Management Functions

### ISSUE THREAD

**Issue by edlich** [edlich/clarango#7]
The ArangoDB shows some User Management Functions:
http://docs.arangodb.org/HttpUserManagement/README.html
Hence Clarango needs a user.clj file to support them (or add them to admin.clj).
There are just six calls to implement:
* Create
* Replace
* Update
* Remove
* Fetch
They should be easy to implement with the http-, core- and uri-utility tools.

**Comment by mikeholmesuk** [comment]
Hi. I could do with this feature so I'm happy to pick this up. Will submit a pull request over the next couple of days. One extra feature that i think is worth including is an 'exists?' function. I'll add that to the database namespace to be consistent with the rest of the library.

**Comment by edlich** [comment]
I am sure this would be awesome (thought this would already exists?!)

**Comment by Lepetere** [comment]
cool :+1:

**Comment by mikeholmesuk** [comment]
Raised pull request (https://github.com/edlich/clarango/pull/13). I added the exists? function to the user namespace as it made sense once I developed it as I use the 'get-all' function as part of checking. I was a little loathe to create a namespace dependency where it wasn't needed.
